# This workflow will do a clean install of node dependencies using Bun, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.1.3

      - name: Setup bun 🛠️
        uses: oven-sh/setup-bun@v2

      - name: Installing my packages 📦
        run: bun install

      - name: Extract repository name 📦
        run: echo "BASE_PATH=/$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Deploy my app 🚀
        run: bun run deploy
